### ISSUE TITLE
error on lit

### ISSUE THREAD

**Issue by thilinadinith** [blekmus/aws-stable-diffusion#1]
it throws an error here

Building wheel for lit (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/ubuntu/stable-diffusion-webui/venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-jku8wid_/lit/setup.py'"'"'; __file__='"'"'/tmp/pip-install-jku8wid_/lit/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-91z2cn15
       cwd: /tmp/pip-install-jku8wid_/lit/
  Complete output (8 lines):
  /home/ubuntu/stable-diffusion-webui/venv/lib/python3.8/site-packages/setuptools/dist.py:473: UserWarning: Normalizing '16.0.5post0' to '16.0.5.post0'
    warnings.warn(
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help
  
  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for lit

**Comment by blekmus** [comment]
I just retried this on a whole new instance with the `Deep Learning AMI GPU PyTorch 2.0.1 (Ubuntu 20.04) 20230613` AMI and everything worked perfectly. Did you install `python3.8-venv`?
