### ISSUE TITLE
Notes

### ISSUE THREAD

**Issue by talyaniv** [blekmus/aws-stable-diffusion#2]
First off all - **this is an excellent tutorial!** Worked almost flawlessly, much needed!

## Installation
```
# official webui installation script
bash <(wget -qO- https://raw.githubusercontent.com/AUTOMATIC1111/stable-diffusion-webui/master/webui.sh)
```
This one didn't work for me as is - it broke on line 192 trying to install the stable-diffusion-webui directory under `/dev` instead of the ubuntu home directory. Instead I just download the script, chmod'd it and ran it locally from the ubuntu home with no problem.

## Spot instances

I would ellaborate about spot instances: that they are significantly cheaper and may be kept uninteruped for days and weeks. Things to note:
By default they run in "one time" mode, either from spot fleet request or from the Launch Instance wizard → Advanced Details. "one time" spot instances cannot be stopped when idle. You want them to run in "persistent" mode, where they can be manually stopped and booted just when you need them:
- Click "Launch Instance"
- Choose the AMI, Instance Type etc
- Expand "Advance Details"
- Check "Request Spot Instances"
- Click "Customize" next to the "Request Spot Instances" option
- From Request Type dropdown, choose "Persistent"
Now when the spot instance is launched, it will be stoppable.

I would also recommend backing up the instance periodically by selecting the instance and then Actions → Images and Templates → Create Image. This process may take some time (took me about 30 minutes). Then if the spot instance is interrupted, you can create a totally new instance without the installation hassle.

I wish I had the time to write a Terraform script for the entire process...

**Comment by blekmus** [comment]
Thanks! I made this after being frustrated by the lack of tutorials or any human-readable guide telling me what to do.

I updated the webui installation to just point to the official repo. The command there has changed slightly from what i put on here which might explain what went wrong.

Also added spot instances to the steps too. I don't have a lot of experience with them so tell me if i got anything wrong.

**Comment by talyaniv** [comment]
Great update, thanks!

**Comment by talyaniv** [comment]
Another thing I encountered today - when starting webui, it complains:
`Cannot locate TCMalloc`
This may influence the weights loading time when changing between models.
Solution:
`sudo apt install --no-install-recommends google-perftools`

**Comment by blekmus** [comment]
Added

**Comment by talyaniv** [comment]
Thanks!
